INSERT INTO games (week16, home, away) VALUES ("Sat", "RedSkins", "Titans" );
INSERT INTO games (week16, home, away) VALUES ("Sat", "Ravens", "Chargers" );
INSERT INTO games (week16, home, away) VALUES ("Sun", "Bengals", "Browns" );
INSERT INTO games (week16, home, away) VALUES ("Sun", "Buccaneers", "Cowboys" );
INSERT INTO games (week16, home, away) VALUES ("Sun", "Vikings", "Lions" );
INSERT INTO games (week16, home, away) VALUES ("Sun", "Bills", "Patriots" );
INSERT INTO games (week16, home, away) VALUES ("Sun", "Packers", "Jets" );
INSERT INTO games (week16, home, away) VALUES ("Sun", "Texans", "Eagales" );
INSERT INTO games (week16, home, away) VALUES ("Sun", "Falcons", "Panthers" );
INSERT INTO games (week16, home, away) VALUES ("Sun", "Giants", "Colts" );
INSERT INTO games (week16, home, away) VALUES ("Sun", "Jaguars", "Dolphins" );
INSERT INTO games (week16, home, away) VALUES ("Sun", "Rams", "Cardinals" );
INSERT INTO games (week16, home, away) VALUES ("Sun", "Bears", "49ERS" );
INSERT INTO games (week16, home, away) VALUES ("Sun", "Steelers", "Saints" );
INSERT INTO games (week16, home, away) VALUES ("Sun", "Chiefs", "Seahawks" );
INSERT INTO games (week16, home, away) VALUES ("Sun", "Broncos", "Raiders" );

insert into games (week17, home, away) values ("sun", "raiders", "chiefs");
insert into games (week17, home, away) values ("sun", "dolphins", "bills");
insert into games (week17, home, away) values ("sun", "colts", "titans");
insert into games (week17, home, away) values ("sun", "bears", "vikings");
insert into games (week17, home, away) values ("sun", "brown", "ravens");
insert into games (week17, home, away) values ("sun", "lions", "packers");
insert into games (week17, home, away) values ("sun", "jets", "patriots");
insert into games (week17, home, away) values ("sun", "panther", "saints");
insert into games (week17, home, away) values ("sun", "jaguars", "texans");
insert into games (week17, home, away) values ("sun", "cowboys", "giants");
insert into games (week17, home, away) values ("sun", "eagles", "redskins");
insert into games (week17, home, away) values ("sun", "falcons", "buccaneers");
insert into games (week17, home, away) values ("sun", "bengals", "steelers");
insert into games (week17, home, away) values ("sun", "cardinals", "seahawks");
insert into games (week17, home, away) values ("sun", "49ers", "rams");
insert into games (week17, home, away) values ("sun", "chargers", "broncos");
